config/routes.rb
Offbudget::Application.routes.draw do

  get "dashboards/index"

  get "reports/index"

  get "dailies/index"

  resources                     :budgets
  resources                     :items
  resources                     :incomes
  resources                     :dailies
  resources                     :reports
  resources                     :dashboards
  
  get       'pages/home'
  match     '/budget/update',   :to => 'budgets#update' 
  match     '/item/update',     :to => 'items#update' 
  match     '/income/update',   :to => 'incomes#update' 
  match     '/daily/update',    :to => 'dailies#update'
  match     '/contact',         :to => 'pages#contact'
  match     '/about',           :to => 'pages#about'
  match     '/help',            :to => 'pages#help'
  devise_for                    :users

  root                          :to => 'pages#index'
 
 end
 

app/views/layouts/_footer.html.erb
<footer>
 	<nav class="round">
    	<ul>
			<li><%= link_to "About", about_path %></li>
	      	<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to image_tag("logo.png", :alt => "Sample App", :class => "round"), root_path %>
  <nav class="round">
    <ul>
      	<li><%= link_to "Home", root_path %></li>
      	<li><%= link_to "Help", help_path %></li>
	  	<% if user_signed_in? %>
			<li><%= link_to "#{current_user.email}", edit_user_registration_path %></li>
			<li><%= link_to "Logout", destroy_user_session_path %></li>
		<% else %>
      		<li><%= link_to "Sign in", new_user_session_path %></li>
		<% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_nav_tabs.html.erb
<% if user_signed_in? %>
<div>
	<%= tabs_tag :open_tabs => { :class => "round tab-container" } do |tab| %>
	  	<%= tab.dashboard 	'Dashboard', dashboards_path, :class => "round tab-item tab-dashboard" %>
	  	<%= tab.budget 		'Budgets', budgets_path, :class => "round tab-item tab-budget" %>
	  	<%= tab.daily      	'Daily Expenditure', dailies_path, :class => "round tab-item tab-daily" %>
	  	<%= tab.report      'Report', reports_path, :class => "round tab-item tab-report" %>
	<% end %>
</div>
<% end %>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag 'jquery', 'rails' %>
	<%= javascript_include_tag 'jeditable', 'effects', 'effects_highlight', 'application'%>
	<%= javascript_tag  do -%>
		var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-19485532-1']);
		  _gaq.push(['_trackPageview']);

		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();
	<% end -%>
  </head>
  <body>
    <div class="container">
     	<%= render 'layouts/header' %>
      	<section class="round">
			<div id="notice"></div>
			<%= render 'layouts/nav_tabs' %>
        	<%= yield %>
      	</section>
		<%= render 'layouts/footer' %>
    </div>
  </body>
</html>